### ISSUE TITLE
Upload your recent changes to the game

### ISSUE THREAD

**Issue by adolfintel** [SilentServices/Scrambled-Net#1]
You can't say the game is open source if you don't upload them :)

**Comment by SilentServices** [comment]
Dear Frederico,

I currently can’t upload. I just moved from eclipse to Android Studio and have to familiarize myself with the IntelliJ Environment. I will for sure update the code but I will do it when I feel I have everything set up correctly. Nobody wants another developer publishing sensitive data.

Cheers,

Michael
